language: java

# install S4 dependencies
install:
  - git clone https://github.com/apache/incubator-s4.git
  - cd incubator-s4
  - gradle wrapper
  - gradle install
  - gradle s4-tools::installApp
  - cd ..
  - mvn install -DskipTests=true -B
  - wget "http://www.philippe-fournier-viger.com/spmf/spmf.jar"
  - mvn install:install-file -Dfile=spmf.jar -DgroupId=spmf -DartifactId=spmf -Dversion=1.0 -Dpackaging=jar

script: "mvn -B -Pstorm,s4 test"

notifications:
  email:
  on_success: never
  on_failure: change
